import {
  Type,
  AlignLeft,
  User,
  Mail,
  Phone,
  Hash,
  Globe,
  CheckSquare,
  CircleDot,
  ScrollText,
  ListChecks,
  ChevronDownSquare,
  ThumbsUp,
  Star,
  Gauge,
  SlidersHorizontal,
  ListOrdered,
  Grid3x3,
  Calendar,
  Clock,
  CalendarClock,
  FileUp,
  PenLine,
  Video,
  Table,
  Package,
  Minus,
  ClipboardCheck,
  Signature,
  Repeat,
  EyeOff,
  Sparkles,
  MapPin,
  Flag,
  Search,
  Link2,
  Lightbulb,
  Braces,
} from "lucide-react"
import type { FieldKind } from "@/lib/field-types"
import { cn } from "@/lib/utils"

const ICONS: Record<FieldKind, typeof Type> = {
  short_text: Type,
  long_text: AlignLeft,
  contact_info: User,
  email: Mail,
  phone: Phone,
  number: Hash,
  website: Globe,
  checkbox: CheckSquare,
  single_choice: CircleDot,
  terms: ScrollText,
  multiple_choice: ListChecks,
  dropdown: ChevronDownSquare,
  multiple_choice_dropdown: ChevronDownSquare,
  yes_no: ThumbsUp,
  like_dislike: ThumbsUp,
  star_rating: Star,
  score: Gauge,
  slider: SlidersHorizontal,
  ranking: ListOrdered,
  matrix: Grid3x3,
  date: Calendar,
  time: Clock,
  date_time: CalendarClock,
  file_upload: FileUp,
  content: PenLine,
  embed_video: Video,
  table: Table,
  product: Package,
  section_divider: Minus,
  review: ClipboardCheck,
  signature: Signature,
  repeating_section: Repeat,
  hidden_field: EyeOff,
  ai_analysis: Sparkles,
  city: MapPin,
  country: Flag,
  lookup: Search,
  linked_record: Link2,
  user_profile: User,
  variable: Braces,
  suggestion: Lightbulb,
}

const COLORS: Record<FieldKind, string> = {
  short_text: "text-blue-600",
  long_text: "text-blue-600",
  contact_info: "text-emerald-600",
  email: "text-emerald-600",
  phone: "text-emerald-600",
  number: "text-emerald-600",
  website: "text-emerald-600",
  checkbox: "text-amber-600",
  single_choice: "text-amber-600",
  terms: "text-amber-600",
  multiple_choice: "text-amber-600",
  dropdown: "text-amber-600",
  multiple_choice_dropdown: "text-amber-600",
  yes_no: "text-amber-600",
  like_dislike: "text-amber-600",
  star_rating: "text-rose-600",
  score: "text-rose-600",
  slider: "text-rose-600",
  ranking: "text-rose-600",
  matrix: "text-rose-600",
  date: "text-indigo-600",
  time: "text-indigo-600",
  date_time: "text-indigo-600",
  file_upload: "text-fuchsia-600",
  content: "text-fuchsia-600",
  embed_video: "text-fuchsia-600",
  table: "text-fuchsia-600",
  product: "text-fuchsia-600",
  section_divider: "text-fuchsia-600",
  review: "text-fuchsia-600",
  signature: "text-fuchsia-600",
  repeating_section: "text-fuchsia-600",
  hidden_field: "text-muted-foreground",
  ai_analysis: "text-orange-600",
  city: "text-orange-600",
  country: "text-orange-600",
  lookup: "text-orange-600",
  linked_record: "text-orange-600",
  user_profile: "text-rose-600",
  variable: "text-slate-500",
  suggestion: "text-orange-600",
}

export function FieldIcon({ kind, className }: { kind: FieldKind; className?: string }) {
  const Icon = ICONS[kind]
  return <Icon className={cn("h-4 w-4", COLORS[kind], className)} />
}
